[package]
name = "openbmclapi_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# https://docs.rs/fern/0.6.2/fern/

[[fern]]
version = "0.6.2"
